//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.07 at 12:58:12 AM MSK 
//


package by.it.generate;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Building complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Building">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="selectedTemperatureOfRegion" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="coefficientSForBuild" type="{http://www.it.by/generate/}coefficientSForBuild"/>
 *         &lt;element name="specifyingCoefficientS5" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="nameOfBuilding" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="id.building" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="fk.id.user" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="dateOfBuilding" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="room" type="{http://www.it.by/generate/}Room" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Building", propOrder = {
    "selectedTemperatureOfRegion",
    "coefficientSForBuild",
    "specifyingCoefficientS5",
    "nameOfBuilding",
    "idBuilding",
    "fkIdUser",
    "dateOfBuilding",
    "room"
})
public class Building {

    protected double selectedTemperatureOfRegion;
    @XmlElement(required = true)
    protected CoefficientSForBuild coefficientSForBuild;
    @XmlElement(defaultValue = "1")
    protected double specifyingCoefficientS5;
    @XmlElement(required = true)
    protected String nameOfBuilding;
    @XmlElement(name = "id.building")
    protected short idBuilding;
    @XmlElement(name = "fk.id.user")
    protected short fkIdUser;
    @XmlElement(required = true)
    protected String dateOfBuilding;
    @XmlElement(required = true)
    protected List<Room> room;

    /**
     * Gets the value of the selectedTemperatureOfRegion property.
     * 
     */
    public double getSelectedTemperatureOfRegion() {
        return selectedTemperatureOfRegion;
    }

    /**
     * Sets the value of the selectedTemperatureOfRegion property.
     * 
     */
    public void setSelectedTemperatureOfRegion(double value) {
        this.selectedTemperatureOfRegion = value;
    }

    /**
     * Gets the value of the coefficientSForBuild property.
     * 
     * @return
     *     possible object is
     *     {@link CoefficientSForBuild }
     *     
     */
    public CoefficientSForBuild getCoefficientSForBuild() {
        if (coefficientSForBuild==null)
            this.coefficientSForBuild=new CoefficientSForBuild();
        return coefficientSForBuild;
    }

    /**
     * Sets the value of the coefficientSForBuild property.
     * 
     * @param value
     *     allowed object is
     *     {@link CoefficientSForBuild }
     *     
     */
    public void setCoefficientSForBuild(CoefficientSForBuild value) {
        this.coefficientSForBuild = value;
    }

    /**
     * Gets the value of the specifyingCoefficientS5 property.
     * 
     */
    public double getSpecifyingCoefficientS5() {
        return specifyingCoefficientS5;
    }

    /**
     * Sets the value of the specifyingCoefficientS5 property.
     * 
     */
    public void setSpecifyingCoefficientS5(double value) {
        this.specifyingCoefficientS5 = value;
    }

    /**
     * Gets the value of the nameOfBuilding property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameOfBuilding() {
        return nameOfBuilding;
    }

    /**
     * Sets the value of the nameOfBuilding property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameOfBuilding(String value) {
        this.nameOfBuilding = value;
    }

    /**
     * Gets the value of the idBuilding property.
     * 
     */
    public short getIdBuilding() {
        return idBuilding;
    }

    /**
     * Sets the value of the idBuilding property.
     * 
     */
    public void setIdBuilding(short value) {
        this.idBuilding = value;
    }

    /**
     * Gets the value of the fkIdUser property.
     * 
     */
    public short getFkIdUser() {
        return fkIdUser;
    }

    /**
     * Sets the value of the fkIdUser property.
     * 
     */
    public void setFkIdUser(short value) {
        this.fkIdUser = value;
    }

    /**
     * Gets the value of the dateOfBuilding property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateOfBuilding() {
        return dateOfBuilding;
    }

    /**
     * Sets the value of the dateOfBuilding property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateOfBuilding(String value) {
        this.dateOfBuilding = value;
    }

    /**
     * Gets the value of the room property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the room property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRoom().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Room }
     * 
     * 
     */
    public List<Room> getRoom() {
        if (room == null) {
            room = new ArrayList<Room>();
        }
        return this.room;
    }

}
