//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.28 at 07:17:31 PM MSK 
//


package by.it.generate;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DetermineTheTypeOfFire complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DetermineTheTypeOfFire">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="amountOfCombustionAir" type="{http://www.w3.org/2001/XMLSchema}double" maxOccurs="5"/>
 *         &lt;element name="selectedFlammableSubstances" type="{http://www.w3.org/2001/XMLSchema}double" maxOccurs="5"/>
 *         &lt;element name="selectedWeightOfFlammableSubstances" type="{http://www.w3.org/2001/XMLSchema}double" maxOccurs="5"/>
 *         &lt;element name="selectedAverageSpeedBurnout" type="{http://www.w3.org/2001/XMLSchema}double" maxOccurs="5"/>
 *         &lt;element name="selectedTemperatureOfRegion" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="proemnostOfRoom" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="averageAmountOfCombustionAir" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="specificCriticalAmountOfFireLoad" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="specificValueOfFireLoad" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="PRN" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DetermineTheTypeOfFire", propOrder = {
    "amountOfCombustionAir",
    "selectedFlammableSubstances",
    "selectedWeightOfFlammableSubstances",
    "selectedAverageSpeedBurnout",
    "selectedTemperatureOfRegion",
    "proemnostOfRoom",
    "averageAmountOfCombustionAir",
    "specificCriticalAmountOfFireLoad",
    "specificValueOfFireLoad",
    "prn"
})
public class DetermineTheTypeOfFire {

    @XmlElement(type = Double.class)
    protected List<Double> amountOfCombustionAir;
    @XmlElement(type = Double.class)
    protected List<Double> selectedFlammableSubstances;
    @XmlElement(type = Double.class)
    protected List<Double> selectedWeightOfFlammableSubstances;
    @XmlElement(type = Double.class)
    protected List<Double> selectedAverageSpeedBurnout;
    protected double selectedTemperatureOfRegion;
    protected double proemnostOfRoom;
    protected double averageAmountOfCombustionAir;
    protected double specificCriticalAmountOfFireLoad;
    protected double specificValueOfFireLoad;
    @XmlElement(name = "PRN")
    protected boolean prn;

    /**
     * Gets the value of the amountOfCombustionAir property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the amountOfCombustionAir property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAmountOfCombustionAir().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Double }
     * 
     * 
     */
    public List<Double> getAmountOfCombustionAir() {
        if (amountOfCombustionAir == null) {
            amountOfCombustionAir = new ArrayList<Double>();
        }
        return this.amountOfCombustionAir;
    }

    /**
     * Gets the value of the selectedFlammableSubstances property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the selectedFlammableSubstances property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSelectedFlammableSubstances().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Double }
     * 
     * 
     */
    public List<Double> getSelectedFlammableSubstances() {
        if (selectedFlammableSubstances == null) {
            selectedFlammableSubstances = new ArrayList<Double>();
        }
        return this.selectedFlammableSubstances;
    }

    /**
     * Gets the value of the selectedWeightOfFlammableSubstances property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the selectedWeightOfFlammableSubstances property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSelectedWeightOfFlammableSubstances().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Double }
     * 
     * 
     */
    public List<Double> getSelectedWeightOfFlammableSubstances() {
        if (selectedWeightOfFlammableSubstances == null) {
            selectedWeightOfFlammableSubstances = new ArrayList<Double>();
        }
        return this.selectedWeightOfFlammableSubstances;
    }

    /**
     * Gets the value of the selectedAverageSpeedBurnout property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the selectedAverageSpeedBurnout property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSelectedAverageSpeedBurnout().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Double }
     * 
     * 
     */
    public List<Double> getSelectedAverageSpeedBurnout() {
        if (selectedAverageSpeedBurnout == null) {
            selectedAverageSpeedBurnout = new ArrayList<Double>();
        }
        return this.selectedAverageSpeedBurnout;
    }

    /**
     * Gets the value of the selectedTemperatureOfRegion property.
     * 
     */
    public double getSelectedTemperatureOfRegion() {
        return selectedTemperatureOfRegion;
    }

    /**
     * Sets the value of the selectedTemperatureOfRegion property.
     * 
     */
    public void setSelectedTemperatureOfRegion(double value) {
        this.selectedTemperatureOfRegion = value;
    }

    /**
     * Gets the value of the proemnostOfRoom property.
     * 
     */
    public double getProemnostOfRoom() {
        return proemnostOfRoom;
    }

    /**
     * Sets the value of the proemnostOfRoom property.
     * 
     */
    public void setProemnostOfRoom(double value) {
        this.proemnostOfRoom = value;
    }

    /**
     * Gets the value of the averageAmountOfCombustionAir property.
     * 
     */
    public double getAverageAmountOfCombustionAir() {
        return averageAmountOfCombustionAir;
    }

    /**
     * Sets the value of the averageAmountOfCombustionAir property.
     * 
     */
    public void setAverageAmountOfCombustionAir(double value) {
        this.averageAmountOfCombustionAir = value;
    }

    /**
     * Gets the value of the specificCriticalAmountOfFireLoad property.
     * 
     */
    public double getSpecificCriticalAmountOfFireLoad() {
        return specificCriticalAmountOfFireLoad;
    }

    /**
     * Sets the value of the specificCriticalAmountOfFireLoad property.
     * 
     */
    public void setSpecificCriticalAmountOfFireLoad(double value) {
        this.specificCriticalAmountOfFireLoad = value;
    }

    /**
     * Gets the value of the specificValueOfFireLoad property.
     * 
     */
    public double getSpecificValueOfFireLoad() {
        return specificValueOfFireLoad;
    }

    /**
     * Sets the value of the specificValueOfFireLoad property.
     * 
     */
    public void setSpecificValueOfFireLoad(double value) {
        this.specificValueOfFireLoad = value;
    }

    /**
     * Gets the value of the prn property.
     * 
     */
    public boolean isPRN() {
        return prn;
    }

    /**
     * Sets the value of the prn property.
     * 
     */
    public void setPRN(boolean value) {
        this.prn = value;
    }

}
