//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.29 at 10:55:07 PM MSK 
//


package by.it.generate;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DetermineTheTypeOfFire complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DetermineTheTypeOfFire">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="proemnostOfRoom" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="averageAmountOfCombustionAir" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="specificCriticalAmountOfFireLoad" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="specificValueOfFireLoad" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="PRN" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DetermineTheTypeOfFire", propOrder = {
    "proemnostOfRoom",
    "averageAmountOfCombustionAir",
    "specificCriticalAmountOfFireLoad",
    "specificValueOfFireLoad",
    "prn"
})
public class DetermineTheTypeOfFire {

    protected double proemnostOfRoom;
    protected double averageAmountOfCombustionAir;
    protected double specificCriticalAmountOfFireLoad;
    protected double specificValueOfFireLoad;
    @XmlElement(name = "PRN")
    protected boolean prn;

    /**
     * Gets the value of the proemnostOfRoom property.
     * 
     */
    public double getProemnostOfRoom() {
        return proemnostOfRoom;
    }

    /**
     * Sets the value of the proemnostOfRoom property.
     * 
     */
    public void setProemnostOfRoom(double value) {
        this.proemnostOfRoom = value;
    }

    /**
     * Gets the value of the averageAmountOfCombustionAir property.
     * 
     */
    public double getAverageAmountOfCombustionAir() {
        return averageAmountOfCombustionAir;
    }

    /**
     * Sets the value of the averageAmountOfCombustionAir property.
     * 
     */
    public void setAverageAmountOfCombustionAir(double value) {
        this.averageAmountOfCombustionAir = value;
    }

    /**
     * Gets the value of the specificCriticalAmountOfFireLoad property.
     * 
     */
    public double getSpecificCriticalAmountOfFireLoad() {
        return specificCriticalAmountOfFireLoad;
    }

    /**
     * Sets the value of the specificCriticalAmountOfFireLoad property.
     * 
     */
    public void setSpecificCriticalAmountOfFireLoad(double value) {
        this.specificCriticalAmountOfFireLoad = value;
    }

    /**
     * Gets the value of the specificValueOfFireLoad property.
     * 
     */
    public double getSpecificValueOfFireLoad() {
        return specificValueOfFireLoad;
    }

    /**
     * Sets the value of the specificValueOfFireLoad property.
     * 
     */
    public void setSpecificValueOfFireLoad(double value) {
        this.specificValueOfFireLoad = value;
    }

    /**
     * Gets the value of the prn property.
     * 
     */
    public boolean isPRN() {
        return prn;
    }

    /**
     * Sets the value of the prn property.
     * 
     */
    public void setPRN(boolean value) {
        this.prn = value;
    }

}
