//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.07 at 12:58:12 AM MSK 
//


package by.it.generate;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for IntegratedThermalAndTechnicalParameters complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IntegratedThermalAndTechnicalParameters">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="maximumMeanBulkTemperature" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="durationOfFireSurround" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="timeReachMaximumMeanBulkTemperature" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="maximumAverageTemperatureOfWallSurface" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="timeToReachMaximumTemperatureOfWallSurface" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="averageMaximumTemperatureOfSlab" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="timeToReachMaximumTemperatureOfSlabSurface" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IntegratedThermalAndTechnicalParameters", propOrder = {
    "maximumMeanBulkTemperature",
    "durationOfFireSurround",
    "timeReachMaximumMeanBulkTemperature",
    "maximumAverageTemperatureOfWallSurface",
    "timeToReachMaximumTemperatureOfWallSurface",
    "averageMaximumTemperatureOfSlab",
    "timeToReachMaximumTemperatureOfSlabSurface"
})
public class IntegratedThermalAndTechnicalParameters {

    protected double maximumMeanBulkTemperature;
    protected double durationOfFireSurround;
    protected double timeReachMaximumMeanBulkTemperature;
    protected double maximumAverageTemperatureOfWallSurface;
    protected double timeToReachMaximumTemperatureOfWallSurface;
    protected double averageMaximumTemperatureOfSlab;
    protected double timeToReachMaximumTemperatureOfSlabSurface;

    /**
     * Gets the value of the maximumMeanBulkTemperature property.
     * 
     */
    public double getMaximumMeanBulkTemperature() {
        return maximumMeanBulkTemperature;
    }

    /**
     * Sets the value of the maximumMeanBulkTemperature property.
     * 
     */
    public void setMaximumMeanBulkTemperature(double value) {
        this.maximumMeanBulkTemperature = value;
    }

    /**
     * Gets the value of the durationOfFireSurround property.
     * 
     */
    public double getDurationOfFireSurround() {
        return durationOfFireSurround;
    }

    /**
     * Sets the value of the durationOfFireSurround property.
     * 
     */
    public void setDurationOfFireSurround(double value) {
        this.durationOfFireSurround = value;
    }

    /**
     * Gets the value of the timeReachMaximumMeanBulkTemperature property.
     * 
     */
    public double getTimeReachMaximumMeanBulkTemperature() {
        return timeReachMaximumMeanBulkTemperature;
    }

    /**
     * Sets the value of the timeReachMaximumMeanBulkTemperature property.
     * 
     */
    public void setTimeReachMaximumMeanBulkTemperature(double value) {
        this.timeReachMaximumMeanBulkTemperature = value;
    }

    /**
     * Gets the value of the maximumAverageTemperatureOfWallSurface property.
     * 
     */
    public double getMaximumAverageTemperatureOfWallSurface() {
        return maximumAverageTemperatureOfWallSurface;
    }

    /**
     * Sets the value of the maximumAverageTemperatureOfWallSurface property.
     * 
     */
    public void setMaximumAverageTemperatureOfWallSurface(double value) {
        this.maximumAverageTemperatureOfWallSurface = value;
    }

    /**
     * Gets the value of the timeToReachMaximumTemperatureOfWallSurface property.
     * 
     */
    public double getTimeToReachMaximumTemperatureOfWallSurface() {
        return timeToReachMaximumTemperatureOfWallSurface;
    }

    /**
     * Sets the value of the timeToReachMaximumTemperatureOfWallSurface property.
     * 
     */
    public void setTimeToReachMaximumTemperatureOfWallSurface(double value) {
        this.timeToReachMaximumTemperatureOfWallSurface = value;
    }

    /**
     * Gets the value of the averageMaximumTemperatureOfSlab property.
     * 
     */
    public double getAverageMaximumTemperatureOfSlab() {
        return averageMaximumTemperatureOfSlab;
    }

    /**
     * Sets the value of the averageMaximumTemperatureOfSlab property.
     * 
     */
    public void setAverageMaximumTemperatureOfSlab(double value) {
        this.averageMaximumTemperatureOfSlab = value;
    }

    /**
     * Gets the value of the timeToReachMaximumTemperatureOfSlabSurface property.
     * 
     */
    public double getTimeToReachMaximumTemperatureOfSlabSurface() {
        return timeToReachMaximumTemperatureOfSlabSurface;
    }

    /**
     * Sets the value of the timeToReachMaximumTemperatureOfSlabSurface property.
     * 
     */
    public void setTimeToReachMaximumTemperatureOfSlabSurface(double value) {
        this.timeToReachMaximumTemperatureOfSlabSurface = value;
    }

}
