//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.07 at 12:58:12 AM MSK 
//


package by.it.generate;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the by.it.generate package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: by.it.generate
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link User }
     * 
     */
    public User createUser() {
        return new User();
    }

    /**
     * Create an instance of {@link Building }
     * 
     */
    public Building createBuilding() {
        return new Building();
    }

    /**
     * Create an instance of {@link CoefficientSForRoom }
     * 
     */
    public CoefficientSForRoom createCoefficientSForRoom() {
        return new CoefficientSForRoom();
    }

    /**
     * Create an instance of {@link FlammableSubstance }
     * 
     */
    public FlammableSubstance createFlammableSubstance() {
        return new FlammableSubstance();
    }

    /**
     * Create an instance of {@link CommonParameters }
     * 
     */
    public CommonParameters createCommonParameters() {
        return new CommonParameters();
    }

    /**
     * Create an instance of {@link DetermineTheTypeOfFire }
     * 
     */
    public DetermineTheTypeOfFire createDetermineTheTypeOfFire() {
        return new DetermineTheTypeOfFire();
    }

    /**
     * Create an instance of {@link Aperture }
     * 
     */
    public Aperture createAperture() {
        return new Aperture();
    }

    /**
     * Create an instance of {@link SubstancesOfRoom }
     * 
     */
    public SubstancesOfRoom createSubstancesOfRoom() {
        return new SubstancesOfRoom();
    }

    /**
     * Create an instance of {@link CoefficientSForBuild }
     * 
     */
    public CoefficientSForBuild createCoefficientSForBuild() {
        return new CoefficientSForBuild();
    }

    /**
     * Create an instance of {@link ChangeInTemperatureOfSlab }
     * 
     */
    public ChangeInTemperatureOfSlab createChangeInTemperatureOfSlab() {
        return new ChangeInTemperatureOfSlab();
    }

    /**
     * Create an instance of {@link ChangeInMeanBulkTemperature }
     * 
     */
    public ChangeInMeanBulkTemperature createChangeInMeanBulkTemperature() {
        return new ChangeInMeanBulkTemperature();
    }

    /**
     * Create an instance of {@link ChangeInTemperatureOfWalls }
     * 
     */
    public ChangeInTemperatureOfWalls createChangeInTemperatureOfWalls() {
        return new ChangeInTemperatureOfWalls();
    }

    /**
     * Create an instance of {@link Room }
     * 
     */
    public Room createRoom() {
        return new Room();
    }

    /**
     * Create an instance of {@link IntegratedThermalAndTechnicalParameters }
     * 
     */
    public IntegratedThermalAndTechnicalParameters createIntegratedThermalAndTechnicalParameters() {
        return new IntegratedThermalAndTechnicalParameters();
    }

    /**
     * Create an instance of {@link ParametersCalculatedFireLoad }
     * 
     */
    public ParametersCalculatedFireLoad createParametersCalculatedFireLoad() {
        return new ParametersCalculatedFireLoad();
    }

}
