//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.07 at 12:58:12 AM MSK 
//


package by.it.generate;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Room complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Room">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id.room" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="fk.id.building" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="commonParameters" type="{http://www.it.by/generate/}CommonParameters"/>
 *         &lt;element name="coefficientSForRoom" type="{http://www.it.by/generate/}CoefficientSForRoom"/>
 *         &lt;element name="aperture" type="{http://www.it.by/generate/}Aperture" maxOccurs="unbounded"/>
 *         &lt;element name="parametersCalculatedFireLoad" type="{http://www.it.by/generate/}ParametersCalculatedFireLoad"/>
 *         &lt;element name="substancesOfRoom" type="{http://www.it.by/generate/}SubstancesOfRoom" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="determineTheTypeOfFire" type="{http://www.it.by/generate/}DetermineTheTypeOfFire"/>
 *         &lt;element name="integratedThermalAndTechnicalParameters" type="{http://www.it.by/generate/}IntegratedThermalAndTechnicalParameters"/>
 *         &lt;element name="changeInMeanBulkTemperature" type="{http://www.it.by/generate/}ChangeInMeanBulkTemperature"/>
 *         &lt;element name="changeInTemperatureOfWalls" type="{http://www.it.by/generate/}ChangeInTemperatureOfWalls"/>
 *         &lt;element name="changeInTemperatureOfSlab" type="{http://www.it.by/generate/}ChangeInTemperatureOfSlab"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Room", propOrder = {
    "idRoom",
    "fkIdBuilding",
    "commonParameters",
    "coefficientSForRoom",
    "aperture",
    "parametersCalculatedFireLoad",
    "substancesOfRoom",
    "determineTheTypeOfFire",
    "integratedThermalAndTechnicalParameters",
    "changeInMeanBulkTemperature",
    "changeInTemperatureOfWalls",
    "changeInTemperatureOfSlab"
})
public class Room {

    @XmlElement(name = "id.room")
    protected short idRoom;
    @XmlElement(name = "fk.id.building")
    protected short fkIdBuilding;
    @XmlElement(required = true)
    protected CommonParameters commonParameters;
    @XmlElement(required = true)
    protected CoefficientSForRoom coefficientSForRoom;
    @XmlElement(required = true)
    protected List<Aperture> aperture;
    @XmlElement(required = true)
    protected ParametersCalculatedFireLoad parametersCalculatedFireLoad;
    protected List<SubstancesOfRoom> substancesOfRoom;
    @XmlElement(required = true)
    protected DetermineTheTypeOfFire determineTheTypeOfFire;
    @XmlElement(required = true)
    protected IntegratedThermalAndTechnicalParameters integratedThermalAndTechnicalParameters;
    @XmlElement(required = true)
    protected ChangeInMeanBulkTemperature changeInMeanBulkTemperature;
    @XmlElement(required = true)
    protected ChangeInTemperatureOfWalls changeInTemperatureOfWalls;
    @XmlElement(required = true)
    protected ChangeInTemperatureOfSlab changeInTemperatureOfSlab;

    /**
     * Gets the value of the idRoom property.
     * 
     */
    public short getIdRoom() {
        return idRoom;
    }

    /**
     * Sets the value of the idRoom property.
     * 
     */
    public void setIdRoom(short value) {
        this.idRoom = value;
    }

    /**
     * Gets the value of the fkIdBuilding property.
     * 
     */
    public short getFkIdBuilding() {
        return fkIdBuilding;
    }

    /**
     * Sets the value of the fkIdBuilding property.
     * 
     */
    public void setFkIdBuilding(short value) {
        this.fkIdBuilding = value;
    }

    /**
     * Gets the value of the commonParameters property.
     * 
     * @return
     *     possible object is
     *     {@link CommonParameters }
     *     
     */
    public CommonParameters getCommonParameters() {
        if (commonParameters==null)
            this.commonParameters=new CommonParameters();
        return commonParameters;
    }

    /**
     * Sets the value of the commonParameters property.
     * 
     * @param value
     *     allowed object is
     *     {@link CommonParameters }
     *     
     */
    public void setCommonParameters(CommonParameters value) {
        this.commonParameters = value;
    }

    /**
     * Gets the value of the coefficientSForRoom property.
     * 
     * @return
     *     possible object is
     *     {@link CoefficientSForRoom }
     *     
     */
    public CoefficientSForRoom getCoefficientSForRoom() {
        if (coefficientSForRoom==null)
            this.coefficientSForRoom=new CoefficientSForRoom();
        return coefficientSForRoom;
    }

    /**
     * Sets the value of the coefficientSForRoom property.
     * 
     * @param value
     *     allowed object is
     *     {@link CoefficientSForRoom }
     *     
     */
    public void setCoefficientSForRoom(CoefficientSForRoom value) {
        this.coefficientSForRoom = value;
    }

    /**
     * Gets the value of the aperture property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the aperture property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAperture().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Aperture }
     * 
     * 
     */
    public List<Aperture> getAperture() {
        if (aperture == null) {
            aperture = new ArrayList<Aperture>();
        }
        return this.aperture;
    }

    /**
     * Gets the value of the parametersCalculatedFireLoad property.
     * 
     * @return
     *     possible object is
     *     {@link ParametersCalculatedFireLoad }
     *     
     */
    public ParametersCalculatedFireLoad getParametersCalculatedFireLoad() {
        if (parametersCalculatedFireLoad==null)
            this.parametersCalculatedFireLoad=new ParametersCalculatedFireLoad();
        return parametersCalculatedFireLoad;
    }

    /**
     * Sets the value of the parametersCalculatedFireLoad property.
     * 
     * @param value
     *     allowed object is
     *     {@link ParametersCalculatedFireLoad }
     *     
     */
    public void setParametersCalculatedFireLoad(ParametersCalculatedFireLoad value) {
        this.parametersCalculatedFireLoad = value;
    }

    /**
     * Gets the value of the substancesOfRoom property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the substancesOfRoom property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSubstancesOfRoom().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SubstancesOfRoom }
     * 
     * 
     */
    public List<SubstancesOfRoom> getSubstancesOfRoom() {
        if (substancesOfRoom == null) {
            substancesOfRoom = new ArrayList<SubstancesOfRoom>();
        }
        return this.substancesOfRoom;
    }

    /**
     * Gets the value of the determineTheTypeOfFire property.
     * 
     * @return
     *     possible object is
     *     {@link DetermineTheTypeOfFire }
     *     
     */
    public DetermineTheTypeOfFire getDetermineTheTypeOfFire() {
        if (determineTheTypeOfFire==null)
            this.determineTheTypeOfFire=new DetermineTheTypeOfFire();
        return determineTheTypeOfFire;
    }

    /**
     * Sets the value of the determineTheTypeOfFire property.
     * 
     * @param value
     *     allowed object is
     *     {@link DetermineTheTypeOfFire }
     *     
     */
    public void setDetermineTheTypeOfFire(DetermineTheTypeOfFire value) {
        this.determineTheTypeOfFire = value;
    }

    /**
     * Gets the value of the integratedThermalAndTechnicalParameters property.
     * 
     * @return
     *     possible object is
     *     {@link IntegratedThermalAndTechnicalParameters }
     *     
     */
    public IntegratedThermalAndTechnicalParameters getIntegratedThermalAndTechnicalParameters() {
        if (integratedThermalAndTechnicalParameters==null)
            this.integratedThermalAndTechnicalParameters=new IntegratedThermalAndTechnicalParameters();
        return integratedThermalAndTechnicalParameters;
    }

    /**
     * Sets the value of the integratedThermalAndTechnicalParameters property.
     * 
     * @param value
     *     allowed object is
     *     {@link IntegratedThermalAndTechnicalParameters }
     *     
     */
    public void setIntegratedThermalAndTechnicalParameters(IntegratedThermalAndTechnicalParameters value) {
        this.integratedThermalAndTechnicalParameters = value;
    }

    /**
     * Gets the value of the changeInMeanBulkTemperature property.
     * 
     * @return
     *     possible object is
     *     {@link ChangeInMeanBulkTemperature }
     *     
     */
    public ChangeInMeanBulkTemperature getChangeInMeanBulkTemperature() {
        if (changeInMeanBulkTemperature==null)
            this.changeInMeanBulkTemperature=new ChangeInMeanBulkTemperature();
        return changeInMeanBulkTemperature;
    }

    /**
     * Sets the value of the changeInMeanBulkTemperature property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChangeInMeanBulkTemperature }
     *     
     */
    public void setChangeInMeanBulkTemperature(ChangeInMeanBulkTemperature value) {
        this.changeInMeanBulkTemperature = value;
    }

    /**
     * Gets the value of the changeInTemperatureOfWalls property.
     * 
     * @return
     *     possible object is
     *     {@link ChangeInTemperatureOfWalls }
     *     
     */
    public ChangeInTemperatureOfWalls getChangeInTemperatureOfWalls() {
        if (changeInTemperatureOfWalls==null)
            this.changeInTemperatureOfWalls=new ChangeInTemperatureOfWalls();
        return changeInTemperatureOfWalls;
    }

    /**
     * Sets the value of the changeInTemperatureOfWalls property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChangeInTemperatureOfWalls }
     *     
     */
    public void setChangeInTemperatureOfWalls(ChangeInTemperatureOfWalls value) {
        this.changeInTemperatureOfWalls = value;
    }

    /**
     * Gets the value of the changeInTemperatureOfSlab property.
     * 
     * @return
     *     possible object is
     *     {@link ChangeInTemperatureOfSlab }
     *     
     */
    public ChangeInTemperatureOfSlab getChangeInTemperatureOfSlab() {
        if (changeInTemperatureOfSlab==null)
            this.changeInTemperatureOfSlab=new ChangeInTemperatureOfSlab();
        return changeInTemperatureOfSlab;
    }

    /**
     * Sets the value of the changeInTemperatureOfSlab property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChangeInTemperatureOfSlab }
     *     
     */
    public void setChangeInTemperatureOfSlab(ChangeInTemperatureOfSlab value) {
        this.changeInTemperatureOfSlab = value;
    }

}
