//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.05 at 10:27:01 PM MSK 
//


package by.it.generate;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Room complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Room">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="commonParameters" type="{http://www.it.by/generate/}CommonParameters"/>
 *         &lt;element name="aperture" type="{http://www.it.by/generate/}Aperture" maxOccurs="unbounded"/>
 *         &lt;element name="parametersCalculatedFireLoad" type="{http://www.it.by/generate/}ParametersCalculatedFireLoad"/>
 *         &lt;element name="flammableSubstance" type="{http://www.it.by/generate/}FlammableSubstance" maxOccurs="unbounded"/>
 *         &lt;element name="determineTheTypeOfFire" type="{http://www.it.by/generate/}DetermineTheTypeOfFire"/>
 *         &lt;element name="integratedThermalAndTechnicalParameters" type="{http://www.it.by/generate/}IntegratedThermalAndTechnicalParameters"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Room", propOrder = {
    "commonParameters",
    "aperture",
    "parametersCalculatedFireLoad",
    "flammableSubstance",
    "determineTheTypeOfFire",
    "integratedThermalAndTechnicalParameters"
})
public class Room {

    @XmlElement(required = true)
    protected CommonParameters commonParameters;
    @XmlElement(required = true)
    protected List<Aperture> aperture;
    @XmlElement(required = true)
    protected ParametersCalculatedFireLoad parametersCalculatedFireLoad;
    @XmlElement(required = true)
    protected List<FlammableSubstance> flammableSubstance;
    @XmlElement(required = true)
    protected DetermineTheTypeOfFire determineTheTypeOfFire;
    @XmlElement(required = true)
    protected IntegratedThermalAndTechnicalParameters integratedThermalAndTechnicalParameters;

    /**
     * Gets the value of the commonParameters property.
     * 
     * @return
     *     possible object is
     *     {@link CommonParameters }
     *     
     */
    public CommonParameters getCommonParameters() {
        return commonParameters;
    }

    /**
     * Sets the value of the commonParameters property.
     * 
     * @param value
     *     allowed object is
     *     {@link CommonParameters }
     *     
     */
    public void setCommonParameters(CommonParameters value) {
        this.commonParameters = value;
    }

    /**
     * Gets the value of the aperture property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the aperture property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAperture().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Aperture }
     * 
     * 
     */
    public List<Aperture> getAperture() {
        if (aperture == null) {
            aperture = new ArrayList<Aperture>();
        }
        return this.aperture;
    }

    /**
     * Gets the value of the parametersCalculatedFireLoad property.
     * 
     * @return
     *     possible object is
     *     {@link ParametersCalculatedFireLoad }
     *     
     */
    public ParametersCalculatedFireLoad getParametersCalculatedFireLoad() {
        return parametersCalculatedFireLoad;
    }

    /**
     * Sets the value of the parametersCalculatedFireLoad property.
     * 
     * @param value
     *     allowed object is
     *     {@link ParametersCalculatedFireLoad }
     *     
     */
    public void setParametersCalculatedFireLoad(ParametersCalculatedFireLoad value) {
        this.parametersCalculatedFireLoad = value;
    }

    /**
     * Gets the value of the flammableSubstance property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the flammableSubstance property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFlammableSubstance().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FlammableSubstance }
     * 
     * 
     */
    public List<FlammableSubstance> getFlammableSubstance() {
        if (flammableSubstance == null) {
            flammableSubstance = new ArrayList<FlammableSubstance>();
        }
        return this.flammableSubstance;
    }

    /**
     * Gets the value of the determineTheTypeOfFire property.
     * 
     * @return
     *     possible object is
     *     {@link DetermineTheTypeOfFire }
     *     
     */
    public DetermineTheTypeOfFire getDetermineTheTypeOfFire() {
        return determineTheTypeOfFire;
    }

    /**
     * Sets the value of the determineTheTypeOfFire property.
     * 
     * @param value
     *     allowed object is
     *     {@link DetermineTheTypeOfFire }
     *     
     */
    public void setDetermineTheTypeOfFire(DetermineTheTypeOfFire value) {
        this.determineTheTypeOfFire = value;
    }

    /**
     * Gets the value of the integratedThermalAndTechnicalParameters property.
     * 
     * @return
     *     possible object is
     *     {@link IntegratedThermalAndTechnicalParameters }
     *     
     */
    public IntegratedThermalAndTechnicalParameters getIntegratedThermalAndTechnicalParameters() {
        return integratedThermalAndTechnicalParameters;
    }

    /**
     * Sets the value of the integratedThermalAndTechnicalParameters property.
     * 
     * @param value
     *     allowed object is
     *     {@link IntegratedThermalAndTechnicalParameters }
     *     
     */
    public void setIntegratedThermalAndTechnicalParameters(IntegratedThermalAndTechnicalParameters value) {
        this.integratedThermalAndTechnicalParameters = value;
    }

}
