//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.07 at 12:58:12 AM MSK 
//


package by.it.generate;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SubstancesOfRoom complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SubstancesOfRoom">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id.substancesOfRoom" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="fk.id.substance" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="fk.id.room" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="flammableSubstance" type="{http://www.it.by/generate/}FlammableSubstance"/>
 *         &lt;element name="weight" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SubstancesOfRoom", propOrder = {
    "idSubstancesOfRoom",
    "fkIdSubstance",
    "fkIdRoom",
    "flammableSubstance",
    "weight"
})
public class SubstancesOfRoom {

    @XmlElement(name = "id.substancesOfRoom")
    protected short idSubstancesOfRoom;
    @XmlElement(name = "fk.id.substance")
    protected short fkIdSubstance;
    @XmlElement(name = "fk.id.room")
    protected short fkIdRoom;
    @XmlElement(required = true)
    protected FlammableSubstance flammableSubstance;
    protected double weight;

    /**
     * Gets the value of the idSubstancesOfRoom property.
     * 
     */
    public short getIdSubstancesOfRoom() {
        return idSubstancesOfRoom;
    }

    /**
     * Sets the value of the idSubstancesOfRoom property.
     * 
     */
    public void setIdSubstancesOfRoom(short value) {
        this.idSubstancesOfRoom = value;
    }

    /**
     * Gets the value of the fkIdSubstance property.
     * 
     */
    public short getFkIdSubstance() {
        return fkIdSubstance;
    }

    /**
     * Sets the value of the fkIdSubstance property.
     * 
     */
    public void setFkIdSubstance(short value) {
        this.fkIdSubstance = value;
    }

    /**
     * Gets the value of the fkIdRoom property.
     * 
     */
    public short getFkIdRoom() {
        return fkIdRoom;
    }

    /**
     * Sets the value of the fkIdRoom property.
     * 
     */
    public void setFkIdRoom(short value) {
        this.fkIdRoom = value;
    }

    /**
     * Gets the value of the flammableSubstance property.
     * 
     * @return
     *     possible object is
     *     {@link FlammableSubstance }
     *     
     */
    public FlammableSubstance getFlammableSubstance() {
        if (flammableSubstance==null)
            this.flammableSubstance=new FlammableSubstance();
        return flammableSubstance;
    }

    /**
     * Sets the value of the flammableSubstance property.
     * 
     * @param value
     *     allowed object is
     *     {@link FlammableSubstance }
     *     
     */
    public void setFlammableSubstance(FlammableSubstance value) {
        this.flammableSubstance = value;
    }

    /**
     * Gets the value of the weight property.
     * 
     */
    public double getWeight() {
        return weight;
    }

    /**
     * Sets the value of the weight property.
     * 
     */
    public void setWeight(double value) {
        this.weight = value;
    }

}
